# Generated by Django 3.0.3 on 2020-07-23 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robotchat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=10)),
                ('like', models.IntegerField()),
                ('dislike', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
                ('anonymous', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='user_info',
            name='username',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_dislike', models.BooleanField()),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='robotchat.message')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='robotchat.user_info')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='robotchat.user_info'),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('anonymous', models.BooleanField()),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='robotchat.message')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='robotchat.user_info')),
            ],
        ),
    ]
