# Generated by Django 3.0.3 on 2020-07-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotchat', '0002_auto_20200723_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='briefInfo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
